alias ls='ls -CF --color'
alias ll='ls -la'
alias la='ls -A'
alias l='ls'
alias c='clear'
alias df='df -H -T | grep -v -E "tmpfs|overlay"'
alias neofetch='clear;neofetch;cowsay "BTW I use Debian"'
alias sub='du -sh ./*'
