alias ll='ls -lh'
alias la='ls -lha'

alias c='clear'
alias df='df -H -T | grep -v -E "tmpfs|overlay"'
alias neo='clear;neofetch;cowsay "BTW I use Debian"'
alias sub='du -sh ./*'
alias up='sudo pacman -Syu'
#alias up='sudo apt update; sudo apt upgrade'
alias vpnup='sudo systemctl start zerotier-one'
alias vpndown='sudo systemctl stop zerotier-one'
alias gs='git status'
alias gc='git commit -m'
alias gp='git push'
alias ga='git add .'
